# Generated by Django 5.2.17 on 2026-10-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_course_code_classroom_professor_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='access_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
