# Generated by Django 5.2.17 on 2026-10-10 00:55

import classrooms.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_populate_access_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='access_code',
            field=models.CharField(default=classrooms.models.generate_access_code, max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Use exactly 6 uppercase letters or numbers.', regex='^[A-Z0-9]{6}\\Z')]),
        ),
    ]
